name: Daily Spotify K-Pop ON Save

on:
  schedule:
    - cron: "0 9 * * *"   # KST 18:00 = UTC 09:00
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install requirements
        run: |
          pip install requests beautifulsoup4 pandas openpyxl pytz

      - name: Run script
        run: |
          python scripts/spotify_kpop_on.py

      - name: Commit and push Excel file
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actionsBot"
          git add spotify/*.xlsx
          git commit -m "Daily Spotify scrape - $(date '+%Y-%m-%d')" || echo "No changes to commit"
          git remote set-url origin https://$GH_PAT@github.com/jongwoo-cho/melon.git
          git push origin main
